site_name: KaróKulus
theme:
  name: material
  features:
    # navigaton top bar and header
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes

    
    - toc.follow # table of context
    - navigation.top # back to top bunnton
    - navigation.footer # previous and next page link in the footer
    - content.action.edit # github repo buttons

    - search.suggest
    - search.highlight
    - search.share


  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  language: hu
  logo: assets/images/public/logo.svg
  favicon: assets/images/public/logo.svg
  icon:
    repo: fontawesome/brands/git-alt # github repo icon
    edit: material/pencil # edit page on github icon
    view: material/eye # view page on github icon

plugins:
  - search:
      lang: hu
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - glightbox # lightbox

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
copyright: Copyright &copy; 2022 - 2023 Barna Gergely

repo_url: https://github.com/BarnaGergely/kalkulus-szte
repo_name: BarnaGergely/kalkulus-szte
edit_uri: edit/main/docs/ # set main branch as default url

markdown_extensions:
  - pymdownx.betterem # bold and italic
  - tables
  - footnotes
  
  # list
  - def_list 
  - pymdownx.tasklist:
      custom_checkbox: true

  # images
  - attr_list 
  - md_in_html

  # tool tips
  - abbr
  - pymdownx.snippets

  # admontions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Content tabs
  - pymdownx.tabbed:
      alternate_style: true 

  # math
  - pymdownx.arithmatex: 
      generic: true

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite


extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js